spring:
  application:
    name: customer-service
  zipkin:
    base-url: http://localhost:9411
    # Uncomment the following line if using a specific sender type
    # sender:
    #   type: web
  sleuth:
    sampler:
      probability: 1.0

## Eureka Client Configuration
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eurekaserver.com:8761/eureka/
      

#Enable this while using High Availalbility - Setup Eureka Clustering
eureka:
  client:
    service-url:
      defaultZone: http://eureka-1-server.com:9001/eureka,http://eureka-2-server.com:9002/eureka,http://eureka-3-server.com:9003/eureka



server:
  port: 7001
     
logging:
  level:
    root: INFO

creditcard:
  service:
    url: http://localhost:7002

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream
