spring:
  profiles: default
server:
  port: 8762
eureka:
  instance:
    hostname: default-eureka-server.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    defaultZone: http://default-eureka-server.com:8762/eureka/

---

spring:
  profiles: eureka-1
  application:
    name: eureka-server-clustered
server:
  port: 8001
eureka:
  instance:
    hostname: eureka-1-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-2-server.com:8002/eureka/,http://eureka-3-server.com:8003/eureka/

---
spring:
  profiles: eureka-2
  application:
    name: eureka-server-clustered
server:
  port: 8002
eureka:
  instance:
    hostname: eureka-2-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-1-server.com:8001/eureka/,http://eureka-3-server.com:8003/eureka/

---
spring:
  profiles: eureka-3
  application:
    name: eureka-server-clustered
server:
  port: 8003
eureka:
  instance:
    hostname: eureka-3-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-1-server.com:8001/eureka/,http://eureka-2-server.com:8002/eureka/


