spring:
  application:
    name: creditcard-service
  zipkin:
    base-url: http://localhost:9411
    service:
      name: zipkin
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 7002

logging:
  level:
    root: INFO

#Register as Eureka Client on Discovery Server and Enable this while using Eureka Zone and Zone Affinity

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#     defaultZone: http://eurekaserver.com:8762/eureka/
      
#Enable this while using High Availalbility - Setup Eureka Clustering
eureka:
  client:
    service-url:
      defaultZone: http://eureka-1-server.com:8001/eureka,http://eureka-2-server.com:8002/eureka,http://eureka-3-server.com:8003/eureka

